version: "3.8"

services:

  mysql:
    image: mysql:8.0
    container_name: bank-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bankdb
      MYSQL_USER: bankuser
      MYSQL_PASSWORD: bankpass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-ubankuser", "-pbankpass"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank-backend
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bankdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: bankuser
      SPRING_DATASOURCE_PASSWORD: bankpass

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bank-frontend
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  mysql_data:
